### ISSUE TITLE
Support for dci-p3?

### ISSUE THREAD

**Issue by Headcrabed** [EaryChow/AgX#7]
Currently we only have display p3 support in this repo and blender. But many monitors are using dci-p3 as default calibration profile. So can you add support for dci-p3 to blender?

**Comment by EaryChow** [comment]
Sorry for not answering for that long, I forgot about this until today. I am not going to make any commits to this repo anymore, but you can modify the config file yourself.
Pixel Manager implemented DCI-P3: https://github.com/Joegenco/PixelManager/blob/master/config.ocio

You can copy and modify some of the text blocks quite easily, or I can do it for you:

```
  - !<ColorSpace> #Linear CIE-XYZ DCI
    name: Linear CIE-XYZ DCI
    aliases: [cie_xyz_dci, CIE-XYZ-DCI, Linear CIE-XYZ DCI]
    family: Chromaticity
    equalitygroup:
    bitdepth: 32f
    description: |
      1931 CIE XYZ with adapted DCI illuminant via Bradford
    isdata: false
    from_scene_reference: !<MatrixTransform> {matrix: [ 0.93137082, -0.04181835, 0.00503453, 0, -0.0638608, 1.0589086, 0.00495221, 0, -0.00358392, 0.00889451, 0.94910541, 0, 0, 0, 0, 1]}

  - !<ColorSpace> #Linear DCI-P3 DCI
    name: Linear DCI-P3 DCI
    aliases: []
    family: Chromaticity
    equalitygroup:
    bitdepth: 32f
    description: |
      DCI-P3 Linear space with DCI white point
    isdata: false
    from_scene_reference: !<GroupTransform>
      children:
        - !<ColorSpaceTransform> {src: Linear CIE-XYZ I-E, dst: Linear CIE-XYZ DCI}     
        - !<MatrixTransform> {matrix: [2.7253940305, -1.0180030062, -0.4401631952, 0.0000000000, -0.7951680258, 1.6897320548, 0.0226471906, 0.0000000000, 0.0412418914, -0.0876390192, 1.1009293786, 0.0000000000, 0.0000000000, 0.0000000000, 0.0000000000, 1.0000000000]}
        
  - !<ColorSpace> #DCI-P3 2.6
    name: DCI-P3 2.6
    aliases: []
    family: Power Functions
    equalitygroup:
    bitdepth: 32f
    description: |
      DCI-P3 cinema standard display view.
    isdata: false
    from_scene_reference: !<GroupTransform>
      children:
        - !<ColorSpaceTransform> {src: Linear CIE-XYZ E, dst: Linear DCI-P3 DCI}
        - !<ExponentTransform> {value: 2.6, direction: inverse}
 
   - !<ColorSpace> 
    name: AgX Base DCI-P3
    family: Imagery
    equalitygroup:
    bitdepth: 32f
    description: |
      AgX Base Image Encoding for DCI-P3 Display
    isdata: false
    from_scene_reference: !<GroupTransform>
      children:
        - !<ColorSpaceTransform> {src: Linear CIE-XYZ E, dst: Linear FilmLight E-Gamut}
        - !<AllocationTransform> {allocation: lg2, vars: [-12.47393, 12.5260688117]}
        - !<FileTransform> {src: AgX_Base_P3.cube, interpolation: tetrahedral}
        - !<ExponentTransform> {value: 2.4}
        - !<ColorSpaceTransform> {src: Linear DCI-P3 D65, dst: DCI-P3 2.6}
    to_scene_reference: !<GroupTransform>
      children:
       - !<ColorSpaceTransform> {src: DCI-P3 2.6, dst: Rec.2020}
       - !<ColorSpaceTransform> {src: AgX Base Rec.2020, dst: Linear CIE-XYZ E}
```
Note I just modfied the last block on the fly, haven't tested it, not sure if there is any typo that might prevent it from running.
You can copy and paste the above lines to the "colorspaces:" section, and in the display device section, add a DCI-P3 display and put AgX view transform in it with the space referring to `AgX Base DCI-P3`, should be quite easy to follow the examples of other display devices.

Let me know if you need further help.
